# Generated by Django 3.0.7 on 2020-06-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20200627_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='time',
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
